export const environment = {
  //--output-hashing all
  //ng build --prod --env=prod --aot false
  //npm run build-prod
  //ng build --configuration "production"
  production: true,
  get autoSaveTime(): number { return 300 },
  get userSessionCheckTime(): number { return 7200 },
  get photonotavail_url(): string { return './assets/img/app/Photonotavail.png'; },
  //Test application
  //get autoSaveTime(): number { return 120 },
  //get userSessionCheckTime(): number { return 1800 },

  //Production URL
  //get api_downloadurl(): string { return 'https://fostering.starlight.inc/starlightapi/api/UploadDocuments/GetFile/'; },
  //get api_uploadurl(): string { return 'https://fostering.starlight.inc/starlightapi/api/UploadDocuments/Upload'; },
  //get api_url(): string { return 'https://fostering.starlight.inc/starlightapi'; },
  //get api_uploadeventsgalleryurl(): string { return 'https://fostering.starlight.inc/starlightapi/api/EventsGallery/Upload'; },
  
  //https://fostering.starlight.inc/starlighttestapi
  get api_downloadurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/UploadDocuments/GetFile/'; },
  get api_uploadurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/UploadDocuments/Upload'; },
  get api_url(): string { return 'https://fostering.starlight.inc/starlighttestapi'; },
  get api_uploadeventsgalleryurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/EventsGallery/Upload'; },

  // get api_downloadurl(): string { return 'http://localhost:52622/api/UploadDocuments/GetFile/'; },
  // get api_uploadurl(): string { return 'http://localhost:52622/api/UploadDocuments/Upload'; },
  // get api_url(): string { return 'http://localhost:52622'; },
  //  get api_uploadeventsgalleryurl(): string { return 'http://localhost:52622/api/EventsGallery/Upload'; },

  //Local publish copy
  //get api_downloadurl(): string { return 'http://idrispc/eCarePlusAPI/api/UploadDocuments/GetFile/'; },
  //get api_uploadurl(): string { return 'http://idrispc/eCarePlusAPI/api/UploadDocuments/Upload'; },
  //get api_url(): string { return 'http://idrispc/eCarePlusAPI'; },
  //get api_uploadeventsgalleryurl(): string { return 'http://idrispc/eCarePlusAPI/api/EventsGallery/Upload'; },

  //subdomain fostering below capcha applied.
  //get captchaPublicKey(): string { return '6LeTCFkUAAAAAO1fns3ibo26sbYs3m1AGp86eYxU'; },

  //subdomain holisticfostering,newlifefostering below capcha applied.
  get captchaPublicKey(): string { return '6LdAl2cUAAAAAOY3vPbeQ0x0JwaVxQSst4pYD4cb'; },

  // Production Reports
  /*
  get report_fosterCarerDiaryRecordingURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FCDiaryRecording.aspx?Id=' },
  get report_applicantDetailsByStatusURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantDetailsByStatus.aspx?Id=' },
  get report_childRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildRegister.aspx?Id=' },
  get report_carerRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerRegister.aspx?Id=' },
  get report_carerChronologyURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerChronology.aspx?Id=' },
  get report_childPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildPlacements.aspx?Id=' },
  get report_carerTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerTraining.aspx?Id=' },
  get report_carerTrainingCourseURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerTrainingCourse.aspx?Id=' },
  get report_diaryRecordingByCarerURL(): string { return 'https://fostering.starlight.inc/StarlightReports/DiaryRecordingsByCarer.aspx?Id=' },
  get report_carerImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerImmunisationDetails.aspx?Id=' },
  get report_childMissingPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildMissingPlacements.aspx?Id=' },
  get report_childEducationKeyStageURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildEducationKeyStage.aspx?Id=' },
  get report_childImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildImmunisationDetails.aspx?Id=' },
  get report_carerVacancyURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarersVacancy.aspx?Id=' },
  // CFS Report request
  get report_applicantRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantRenewalChecks.aspx?Id=' },
  get report_applicantReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantReferenceChecks.aspx?Id=' },
  get report_currentApplicantsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CurrentApplicants.aspx?Id=' },
  get report_carerRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerRenewalChecks.aspx?Id=' },
  get report_carerReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerReferenceChecks.aspx?Id=' },
  get report_reg35URL(): string { return 'https://fostering.starlight.inc/StarlightReports/Reg35.aspx?Id=' },
  get report_outcomesRatingURL(): string { return 'https://fostering.starlight.inc/StarlightReports/OutcomesRating.aspx?Id=' },
  get report_childMedicationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildMedicationDetails.aspx?Id=' },
  get report_childIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildIncidents.aspx?Id=' },
  get report_childAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildAllegations.aspx?Id=' },
  get report_childComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildComplaints.aspx?Id=' },
  get report_hrStaffStatChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffStatChecks.aspx?Id=' },
  get report_childReferralsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildReferrals.aspx?Id=' },
  get report_childOOHURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildOOH.aspx?Id=' },
  get report_carerTrainingStatusURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerTrainingStatus.aspx?Id=' },
  get report_annualReviewDatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerAnnualReviewDates.aspx?Id=' },
  get report_carerDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerDaylogEvents.aspx?Id=' },
  get report_childDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildDaylogEvents.aspx?Id=' },
  get report_carerIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerIncidents.aspx?Id=' },
  get report_userLogHistoryURL(): string { return 'https://fostering.starlight.inc/StarlightReports/UserLogHistory.aspx?Id=' },
  get report_activeCarerContactDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ActiveCarerContactDetails.aspx?Id=' },
  get report_claDocumentationURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CLADocumentation.aspx?Id=' },
  get report_fcDiaryRecordingsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FCDiaryRecordings.aspx?Id=' },
  get report_unannouncedHomeVisitURL(): string { return 'https://fostering.starlight.inc/StarlightReports/UnannouncedHomeVisit.aspx?Id=' },
  get report_sourceOfEnquiryURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SourceOfEnquiry.aspx?Id=' },
  get report_applicantStatsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantsStats.aspx?Id=' },
  get report_applicantsAssessmentsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantAssessments.aspx?Id=' },
  get report_applicantsWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantsWithdrawn.aspx?Id=' },
  get report_ihvApplicantWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightReports/IHVApplicantsWithdrawn.aspx?Id=' },
  get report_childReferralStatsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildReferralStats.aspx?Id=' },
  get report_carersBySocialWorkerURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarersBySocialWorker.aspx?Id=' },
  get report_schedule7URL(): string { return 'https://fostering.starlight.inc/StarlightReports/Schedule7.aspx?Id=' },
  get report_childMedicalAppointmentsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildMedicalAppointments.aspx?Id=' },
  get report_shvCarerDatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SHVCarerDates.aspx?Id=' },
  get report_carerAuditURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerAudit.aspx?Id=' },
  get report_nfaReasonsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/NFAReasons.aspx?Id=' },
  get report_childSafecarePolicyURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildSafeCarePolicy.aspx?Id=' },
  get report_carerAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerAllegations.aspx?Id=' },
  get report_carerComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerComplaints.aspx?Id=' },
  get report_hrStaffSupervisionURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffSupervision.aspx?Id=' },
  get report_hrStaffAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffAppraisal.aspx?Id=' },
  get report_hrStaffTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffTraining.aspx?Id=' },
  get report_childEducationInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildEducationInfo.aspx?Id=' },
  get report_childHealthInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildHealthInfo.aspx?Id=' },
  get report_childRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildRespitePlacements.aspx?Id=' },
  get report_ihvOldVersionURL(): string { return 'https://fostering.starlight.inc/StarlightReports/IHVOldVersion.aspx?Id=' },
  get report_advertisingAnalysisURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantAdvertisingAnalysis.aspx?Id=' },
  get report_shvOldVersionTutisURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SHVOldVersionTutis.aspx?Id=' },
  get report_childTherapeuticAssessmentScoreURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildTherapeuticAssessmentScore.aspx?Id=' },
  get report_carerPlacementRefusalURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerPlacementRefusal.aspx?Id=' },
  get report_childReferralInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildReferralInfo.aspx?Id=' },
  get report_claDocumentationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CLADocumentationCategory.aspx?Id=' },
  get report_ecmProgressDatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ECMProgressDates.aspx?Id=' },
  get report_childrenBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildrenBirthday.aspx?Id=' },
  get report_carerBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerBirthday.aspx?Id=' },
  get report_carerPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerPlacements.aspx?Id=' },
  get report_childEducationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildEducationCategory.aspx?Id=' },
  get report_childReportByDischargeReasonURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildReportByDischargeReason.aspx?Id=' },
  get report_fcPaymentsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FCPayments.aspx?Id=' },
  get report_fcInvoiceURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FCInvoice.aspx?Id=' },
  get report_laFinanceURL(): string { return 'https://fostering.starlight.inc/StarlightReports/LAFinance.aspx?Id=' },
  get report_shvOutcomesRatingsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SHVOutcomesRatings.aspx?Id=' },
  get report_carerDBSUpdateServiceURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerDBSUpdateService.aspx?Id=' },
  get report_qaManagementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightReports/QAManagementTracker.aspx?Id=' },
  get report_qaManagementReportURL(): string { return 'https://fostering.starlight.inc/StarlightReports/QAManagementReport.aspx?Id=' },
  get report_carerRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerRespitePlacements.aspx?Id=' },
  get report_carerMedicalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerMedicalChecksReport.aspx?Id=' },
  get report_childrenInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildrenInfo.aspx?Id=' },
  get report_childRiskAssessmentDatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildRiskAssessmentDates.aspx?Id=' },
  get report_backupCarersURL(): string { return 'https://fostering.starlight.inc/StarlightReports/BackupCarers.aspx?Id=' },
  get report_fcAllowanceURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FCAllowance.aspx?Id=' },
  get report_referralsByCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ReferralsByCategory.aspx?Id=' },
  get report_childHospitalizationURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildHospitalization.aspx?Id=' },
  get report_childSHVDatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildSHVDates.aspx?Id=' },
  get report_placementRatesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/PlacementRates.aspx?Id=' },
  get report_staffLeavesURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffLeaves.aspx?Id=' },
  get report_childAuditURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildAudit.aspx?Id=' },
  get report_placementInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/PlacementInfo.aspx?Id=' },
  get report_panelRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightReports/PanelRecommendation.aspx?Id=' },
  get report_reviewOfficerRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ReviewOfficerRecommendation.aspx?Id=' },
  get report_claReviewURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CLAReview.aspx?Id=' },
  get report_childPersonalGoalsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildPersonalGoals.aspx?Id=' },
  get report_carerOOHURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerOOH.aspx?Id=' },
  get report_applicantsStageInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ApplicantsStageInfo.aspx?Id=' },
  get report_fosteringHouseholdURL(): string { return 'https://fostering.starlight.inc/StarlightReports/FosteringHousehold.aspx?Id=' },
  get report_hrPanelMemberAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRPanelMemberAppraisal.aspx?Id=' },
  get report_hrSSWSupervisionActionsURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRSSWSupervisionActions.aspx?Id=' },
  get report_hrStaffBirthdaysURL(): string { return 'https://fostering.starlight.inc/StarlightReports/HRStaffBirthdays.aspx?Id=' },
  get report_placementsByStaffUserURL(): string { return 'https://fostering.starlight.inc/StarlightReports/PlacementsByStaffUser.aspx?Id=' },
  get report_carerStatusInfoURL(): string { return 'https://fostering.starlight.inc/StarlightReports/CarerStatusInfo.aspx?Id=' },
  get report_sswAnnualReviewURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SSWAnnualReview.aspx?Id=' },
  get report_childrensRisksURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildrensRisks.aspx?Id=' },
  get report_placementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildPlacementTracker.aspx?Id=' },
  get report_shvfcsignatureURL(): string { return 'https://fostering.starlight.inc/StarlightReports/SHVFCSignature.aspx?Id=' },
  get report_childecmgoalsphotographURL(): string { return 'https://fostering.starlight.inc/StarlightReports/ChildECMGoalsandPhotograph.aspx?Id=' },
  */
  
  // Demo Reports
  /*
  get report_fosterCarerDiaryRecordingURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FCDiaryRecording.aspx?Id=' },
  get report_applicantDetailsByStatusURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantDetailsByStatus.aspx?Id=' },
  get report_childRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildRegister.aspx?Id=' },
  get report_carerRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerRegister.aspx?Id=' },
  get report_carerChronologyURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerChronology.aspx?Id=' },
  get report_childPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildPlacements.aspx?Id=' },
  get report_carerTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerTraining.aspx?Id=' },
  get report_carerTrainingCourseURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerTrainingCourse.aspx?Id=' },
  get report_diaryRecordingByCarerURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/DiaryRecordingsByCarer.aspx?Id=' },
  get report_carerImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerImmunisationDetails.aspx?Id=' },
  get report_childMissingPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildMissingPlacements.aspx?Id=' },
  get report_childEducationKeyStageURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildEducationKeyStage.aspx?Id=' },
  get report_childImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildImmunisationDetails.aspx?Id=' },
  get report_carerVacancyURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarersVacancy.aspx?Id=' },
  // CFS Report request
  get report_applicantRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantRenewalChecks.aspx?Id=' },
  get report_applicantReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantReferenceChecks.aspx?Id=' },
  get report_currentApplicantsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CurrentApplicants.aspx?Id=' },
  get report_carerRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerRenewalChecks.aspx?Id=' },
  get report_carerReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerReferenceChecks.aspx?Id=' },
  get report_reg35URL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/Reg35.aspx?Id=' },
  get report_outcomesRatingURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/OutcomesRating.aspx?Id=' },
  get report_childMedicationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildMedicationDetails.aspx?Id=' },
  get report_childIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildIncidents.aspx?Id=' },
  get report_childAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildAllegations.aspx?Id=' },
  get report_childComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildComplaints.aspx?Id=' },
  get report_hrStaffStatChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffStatChecks.aspx?Id=' },
  get report_childReferralsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildReferrals.aspx?Id=' },
  get report_childOOHURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildOOH.aspx?Id=' },
  get report_carerTrainingStatusURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerTrainingStatus.aspx?Id=' },
  get report_annualReviewDatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerAnnualReviewDates.aspx?Id=' },
  get report_carerDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerDaylogEvents.aspx?Id=' },
  get report_childDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildDaylogEvents.aspx?Id=' },
  get report_carerIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerIncidents.aspx?Id=' },
  get report_userLogHistoryURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/UserLogHistory.aspx?Id=' },
  get report_activeCarerContactDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ActiveCarerContactDetails.aspx?Id=' },
  get report_claDocumentationURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CLADocumentation.aspx?Id=' },
  get report_fcDiaryRecordingsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FCDiaryRecordings.aspx?Id=' },
  get report_unannouncedHomeVisitURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/UnannouncedHomeVisit.aspx?Id=' },
  get report_sourceOfEnquiryURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SourceOfEnquiry.aspx?Id=' },
  get report_applicantStatsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantsStats.aspx?Id=' },
  get report_applicantsAssessmentsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantAssessments.aspx?Id=' },
  get report_applicantsWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantsWithdrawn.aspx?Id=' },
  get report_ihvApplicantWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/IHVApplicantsWithdrawn.aspx?Id=' },
  get report_childReferralStatsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildReferralStats.aspx?Id=' },
  get report_carersBySocialWorkerURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarersBySocialWorker.aspx?Id=' },
  get report_schedule7URL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/Schedule7.aspx?Id=' },
  get report_childMedicalAppointmentsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildMedicalAppointments.aspx?Id=' },
  get report_shvCarerDatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SHVCarerDates.aspx?Id=' },
  get report_carerAuditURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerAudit.aspx?Id=' },
  get report_nfaReasonsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/NFAReasons.aspx?Id=' },
  get report_childSafecarePolicyURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildSafeCarePolicy.aspx?Id=' },
  get report_carerAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerAllegations.aspx?Id=' },
  get report_carerComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerComplaints.aspx?Id=' },
  get report_hrStaffSupervisionURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffSupervision.aspx?Id=' },
  get report_hrStaffAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffAppraisal.aspx?Id=' },
  get report_hrStaffTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffTraining.aspx?Id=' },
  get report_childEducationInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildEducationInfo.aspx?Id=' },
  get report_childHealthInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildHealthInfo.aspx?Id=' },
  get report_childRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildRespitePlacements.aspx?Id=' },
  get report_ihvOldVersionURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/IHVOldVersion.aspx?Id=' },
  get report_advertisingAnalysisURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantAdvertisingAnalysis.aspx?Id=' },
  get report_shvOldVersionTutisURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SHVOldVersionTutis.aspx?Id=' },
  get report_childTherapeuticAssessmentScoreURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildTherapeuticAssessmentScore.aspx?Id=' },
  get report_carerPlacementRefusalURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerPlacementRefusal.aspx?Id=' },
  get report_childReferralInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildReferralInfo.aspx?Id=' },
  get report_claDocumentationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CLADocumentationCategory.aspx?Id=' },
  get report_ecmProgressDatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ECMProgressDates.aspx?Id=' },
  get report_childrenBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildrenBirthday.aspx?Id=' },
  get report_carerBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerBirthday.aspx?Id=' },
  get report_carerPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerPlacements.aspx?Id=' },
  get report_childEducationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildEducationCategory.aspx?Id=' },
  get report_childReportByDischargeReasonURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildReportByDischargeReason.aspx?Id=' },
  get report_fcPaymentsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FCPayments.aspx?Id=' },
  get report_fcInvoiceURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FCInvoice.aspx?Id=' },
  get report_laFinanceURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/LAFinance.aspx?Id=' },
  get report_shvOutcomesRatingsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SHVOutcomesRatings.aspx?Id=' },
  get report_carerDBSUpdateServiceURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerDBSUpdateService.aspx?Id=' },
  get report_qaManagementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/QAManagementTracker.aspx?Id=' },
  get report_qaManagementReportURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/QAManagementReport.aspx?Id=' },
  get report_carerRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerRespitePlacements.aspx?Id=' },
  get report_carerMedicalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerMedicalChecksReport.aspx?Id=' },
  get report_childrenInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildrenInfo.aspx?Id=' },
  get report_childRiskAssessmentDatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildRiskAssessmentDates.aspx?Id=' },
  get report_backupCarersURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/BackupCarers.aspx?Id=' },
  get report_fcAllowanceURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FCAllowance.aspx?Id=' },
  get report_referralsByCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ReferralsByCategory.aspx?Id=' },
  get report_childHospitalizationURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildHospitalization.aspx?Id=' },
  get report_childSHVDatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildSHVDates.aspx?Id=' },
  get report_placementRatesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/PlacementRates.aspx?Id=' },
  get report_staffLeavesURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffLeaves.aspx?Id=' },
  get report_childAuditURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildAudit.aspx?Id=' },
  get report_placementInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/PlacementInfo.aspx?Id=' },
  get report_panelRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/PanelRecommendation.aspx?Id=' },
  get report_reviewOfficerRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ReviewOfficerRecommendation.aspx?Id=' },
  get report_claReviewURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CLAReview.aspx?Id=' },
  get report_childPersonalGoalsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildPersonalGoals.aspx?Id=' },
  get report_carerOOHURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerOOH.aspx?Id=' },
  get report_applicantsStageInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ApplicantsStageInfo.aspx?Id=' },
  get report_fosteringHouseholdURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/FosteringHousehold.aspx?Id=' },

  get report_hrPanelMemberAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRPanelMemberAppraisal.aspx?Id=' },
  get report_hrSSWSupervisionActionsURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRSSWSupervisionActions.aspx?Id=' },
  get report_hrStaffBirthdaysURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/HRStaffBirthdays.aspx?Id=' },
  get report_placementsByStaffUserURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/PlacementsByStaffUser.aspx?Id=' },
  get report_carerStatusInfoURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/CarerStatusInfo.aspx?Id=' },
  get report_sswAnnualReviewURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SSWAnnualReview.aspx?Id=' },
  get report_childrensRisksURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildrensRisks.aspx?Id=' },
  get report_placementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildPlacementTracker.aspx?Id=' },
  get report_shvfcsignatureURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/SHVFCSignature.aspx?Id=' },
get report_childecmgoalsphotographURL(): string { return 'https://fostering.starlight.inc/StarlightDemoReports/ChildECMGoalsandPhotograph.aspx?Id=' },

  */
  //Test Reports

  get report_fosterCarerDiaryRecordingURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FCDiaryRecording.aspx?Id=' },
  get report_applicantDetailsByStatusURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantDetailsByStatus.aspx?Id=' },
  get report_childRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildRegister.aspx?Id=' },
  get report_carerRegisterURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerRegister.aspx?Id=' },
  get report_carerChronologyURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerChronology.aspx?Id=' },
  get report_childPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildPlacements.aspx?Id=' },
  get report_carerTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerTraining.aspx?Id=' },
  get report_carerTrainingCourseURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerTrainingCourse.aspx?Id=' },
  get report_diaryRecordingByCarerURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/DiaryRecordingsByCarer.aspx?Id=' },
  get report_carerImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerImmunisationDetails.aspx?Id=' },
  get report_childMissingPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildMissingPlacements.aspx?Id=' },
  get report_childEducationKeyStageURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildEducationKeyStage.aspx?Id=' },
  get report_childImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildImmunisationDetails.aspx?Id=' },
  get report_carerVacancyURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarersVacancy.aspx?Id=' },
    // CFS Report request
  get report_applicantRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantRenewalChecks.aspx?Id=' },
  get report_applicantReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantReferenceChecks.aspx?Id=' },
  get report_currentApplicantsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CurrentApplicants.aspx?Id=' },
  get report_carerRenewalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerRenewalChecks.aspx?Id=' },
  get report_carerReferenceChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerReferenceChecks.aspx?Id=' },
  get report_reg35URL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/Reg35.aspx?Id=' },
  get report_outcomesRatingURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/OutcomesRating.aspx?Id=' },
  get report_childMedicationDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildMedicationDetails.aspx?Id=' },
  get report_childIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildIncidents.aspx?Id=' },
  get report_childAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildAllegations.aspx?Id=' },
  get report_childComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildComplaints.aspx?Id=' },
  get report_hrStaffStatChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffStatChecks.aspx?Id=' },
  get report_childReferralsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildReferrals.aspx?Id=' },
  get report_childOOHURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildOOH.aspx?Id=' },
  get report_carerTrainingStatusURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerTrainingStatus.aspx?Id=' },
  get report_annualReviewDatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerAnnualReviewDates.aspx?Id=' },
  get report_carerDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerDaylogEvents.aspx?Id=' },
  get report_childDayLogEventsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildDaylogEvents.aspx?Id=' },
  get report_carerIncidentsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerIncidents.aspx?Id=' },
  get report_userLogHistoryURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/UserLogHistory.aspx?Id=' },
  get report_activeCarerContactDetailsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ActiveCarerContactDetails.aspx?Id=' },
  get report_claDocumentationURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CLADocumentation.aspx?Id=' },
  get report_fcDiaryRecordingsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FCDiaryRecordings.aspx?Id=' },
  get report_unannouncedHomeVisitURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/UnannouncedHomeVisit.aspx?Id=' },
  get report_sourceOfEnquiryURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SourceOfEnquiry.aspx?Id=' },
  get report_applicantStatsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantsStats.aspx?Id=' },
  get report_applicantsAssessmentsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantAssessments.aspx?Id=' },
  get report_applicantsWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantsWithdrawn.aspx?Id=' },
  get report_ihvApplicantWithdrawnURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/IHVApplicantsWithdrawn.aspx?Id=' },
  get report_childReferralStatsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildReferralStats.aspx?Id=' },
  get report_carersBySocialWorkerURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarersBySocialWorker.aspx?Id=' },
  get report_schedule7URL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/Schedule7.aspx?Id=' },
  get report_childMedicalAppointmentsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildMedicalAppointments.aspx?Id=' },
  get report_shvCarerDatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SHVCarerDates.aspx?Id=' },
  get report_carerAuditURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerAudit.aspx?Id=' },
  get report_nfaReasonsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/NFAReasons.aspx?Id=' },
  get report_childSafecarePolicyURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildSafeCarePolicy.aspx?Id=' },
  get report_carerAllegationsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerAllegations.aspx?Id=' },
  get report_carerComplaintsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerComplaints.aspx?Id=' },
  get report_hrStaffSupervisionURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffSupervision.aspx?Id=' },
  get report_hrStaffAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffAppraisal.aspx?Id=' },
  get report_hrStaffTrainingURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffTraining.aspx?Id=' },
  get report_childEducationInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildEducationInfo.aspx?Id=' },
  get report_childHealthInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildHealthInfo.aspx?Id=' },
  get report_childRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildRespitePlacements.aspx?Id=' },
  get report_ihvOldVersionURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/IHVOldVersion.aspx?Id=' },
  get report_advertisingAnalysisURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantAdvertisingAnalysis.aspx?Id=' },
  get report_shvOldVersionTutisURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SHVOldVersionTutis.aspx?Id=' },
  get report_childTherapeuticAssessmentScoreURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildTherapeuticAssessmentScore.aspx?Id=' },
  get report_carerPlacementRefusalURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerPlacementRefusal.aspx?Id=' },
  get report_childReferralInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildReferralInfo.aspx?Id=' },
  get report_claDocumentationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CLADocumentationCategory.aspx?Id=' },
  get report_ecmProgressDatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ECMProgressDates.aspx?Id=' },
  get report_childrenBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildrenBirthday.aspx?Id=' },
  get report_carerBirthdayURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerBirthday.aspx?Id=' },
  get report_carerPlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerPlacements.aspx?Id=' },
  get report_childEducationCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildEducationCategory.aspx?Id=' },
  get report_childReportByDischargeReasonURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildReportByDischargeReason.aspx?Id=' },
  get report_fcPaymentsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FCPayments.aspx?Id=' },
  get report_fcInvoiceURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FCInvoice.aspx?Id=' },
  get report_laFinanceURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/LAFinance.aspx?Id=' },
  get report_shvOutcomesRatingsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SHVOutcomesRatings.aspx?Id=' },
  get report_carerDBSUpdateServiceURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerDBSUpdateService.aspx?Id=' },
  get report_qaManagementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/QAManagementTracker.aspx?Id=' },
  get report_qaManagementReportURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/QAManagementReport.aspx?Id=' },
  get report_carerRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerRespitePlacements.aspx?Id=' },
  get report_carerMedicalChecksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerMedicalChecksReport.aspx?Id=' },
  get report_childrenInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildrenInfo.aspx?Id=' },
  get report_childRiskAssessmentDatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildRiskAssessmentDates.aspx?Id=' },
  get report_backupCarersURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/BackupCarers.aspx?Id=' },
  get report_fcAllowanceURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FCAllowance.aspx?Id=' },
  get report_referralsByCategoryURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ReferralsByCategory.aspx?Id=' },
  get report_childHospitalizationURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildHospitalization.aspx?Id=' },
  get report_childSHVDatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildSHVDates.aspx?Id=' },
  get report_placementRatesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/PlacementRates.aspx?Id=' },
  get report_staffLeavesURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffLeaves.aspx?Id=' },
  get report_childAuditURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildAudit.aspx?Id=' },
  get report_placementInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/PlacementInfo.aspx?Id=' },
  get report_panelRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/PanelRecommendation.aspx?Id=' },
  get report_reviewOfficerRecommendationURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ReviewOfficerRecommendation.aspx?Id=' },
  get report_claReviewURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CLAReview.aspx?Id=' },
  get report_childPersonalGoalsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildPersonalGoals.aspx?Id=' },
  get report_carerOOHURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerOOH.aspx?Id=' },
  get report_applicantsStageInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ApplicantsStageInfo.aspx?Id=' },
  get report_fosteringHouseholdURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/FosteringHousehold.aspx?Id=' },

  get report_hrPanelMemberAppraisalURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRPanelMemberAppraisal.aspx?Id=' },
  get report_hrSSWSupervisionActionsURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRSSWSupervisionActions.aspx?Id=' },
  get report_hrStaffBirthdaysURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/HRStaffBirthdays.aspx?Id=' },
  get report_placementsByStaffUserURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/PlacementsByStaffUser.aspx?Id=' },
  get report_carerStatusInfoURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/CarerStatusInfo.aspx?Id=' },
  get report_sswAnnualReviewURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SSWAnnualReview.aspx?Id=' },
  get report_childrensRisksURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildrensRisks.aspx?Id=' },
  get report_placementTrackerURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildPlacementTracker.aspx?Id=' },
  get report_shvfcsignatureURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/SHVFCSignature.aspx?Id=' },
  get report_childecmgoalsphotographURL(): string { return 'https://fostering.starlight.inc/StarlightTestReports/ChildECMGoalsandPhotograph.aspx?Id=' },

};
