// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.
//Ang 15 version 1.

export const environment = {
  production: false,

  get photonotavail_url(): string { return './assets/img/app/Photonotavail.png'; },
  get api_downloadurl(): string { return 'https://localhost:7065/api/UploadDocuments/GetFile/'; },
  get api_uploadurl(): string { return 'https://localhost:7065/api/UploadDocuments/Upload'; },
  get api_url(): string { return 'https://localhost:7065'; },
  get api_uploadeventsgalleryurl(): string { return 'https://localhost:7065/api/EventsGallery/Upload'; },

  // //https://fostering.starlight.inc/starlighttestapi
  //get api_downloadurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/UploadDocuments/GetFile/'; },
  //get api_uploadurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/UploadDocuments/Upload'; },
  //get api_url(): string { return 'https://fostering.starlight.inc/starlighttestapi'; },
  //get api_uploadeventsgalleryurl(): string { return 'https://fostering.starlight.inc/starlighttestapi/api/EventsGallery/Upload'; },
  //get photonotavail_url(): string { return 'http://localhost:52622'; },

  //To connect the application through other device
  //get api_downloadurl(): string { return 'http://idrispc/eCarePlusAPI/api/UploadDocuments/GetFile/'; },
  //get api_uploadurl(): string { return 'http://idrispc/eCarePlusAPI/api/UploadDocuments/Upload'; },
  //get api_url(): string { return 'http://idrispc/eCarePlusAPI'; },

  //get api_downloadurl(): string { return 'http://localhost/eCarePlusAPI/api/UploadDocuments/GetFile/'; },
  //get api_uploadurl(): string { return 'http://localhost/eCarePlusAPI/api/UploadDocuments/Upload'; },
  //get api_url(): string { return 'http://localhost/eCarePlusAPI'; },

  get captchaPublicKey(): string { return '6Lda2DgUAAAAAHX6RS6q5qDiTEOe99_r1SbxX28B'; },
  get autoSaveTime(): number { return 300 },
  get report_fosterCarerDiaryRecordingURL(): string { return 'http://fostering.starlight.inc/eCarePlusReports/FCDiaryRecording.aspx?Id=' },
  get report_applicantDetailsByStatusURL(): string { return 'http://fostering.starlight.inc/eCarePlusReports/ApplicantDetailsByStatus.aspx?Id=' },
  get report_childRegisterURL(): string { return 'http://fostering.starlight.inc/eCarePlusReports/ChildRegister.aspx?Id=' },
  get report_carerRegisterURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerRegister.aspx?Id=' },
  get report_carerChronologyURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerChronology.aspx?Id=' },
  get report_childPlacementsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildPlacements.aspx?Id=' },
  get report_carerTrainingURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerTraining.aspx?Id=' },
  get report_carerTrainingCourseURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerTrainingCourse.aspx?Id=' },
  get report_diaryRecordingByCarerURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/DiaryRecordingsByCarer.aspx?Id=' },
  get report_carerImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerImmunisationDetails.aspx?Id=' },
  get report_childMissingPlacementsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildMissingPlacements.aspx?Id=' },
  get report_childEducationKeyStageURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildEducationKeyStage.aspx?Id=' },
  get report_childImmunisationDetailsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildImmunisationDetails.aspx?Id=' },
  get report_carerVacancyURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarersVacancy.aspx?Id=' },
  /* CFS Report request */
  get report_applicantRenewalChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantRenewalChecks.aspx?Id=' },
  get report_applicantReferenceChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantReferenceChecks.aspx?Id=' },
  get report_currentApplicantsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CurrentApplicants.aspx?Id=' },
  get report_carerRenewalChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerRenewalChecks.aspx?Id=' },
  get report_carerReferenceChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerReferenceChecks.aspx?Id=' },
  get report_reg35URL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/Reg35.aspx?Id=' },

  get report_outcomesRatingURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/OutcomesRating.aspx?Id=' },
  get report_childMedicationDetailsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildMedicationDetails.aspx?Id=' },
  get report_childIncidentsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildIncidents.aspx?Id=' },
  get report_childAllegationsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildAllegations.aspx?Id=' },
  get report_childComplaintsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildComplaints.aspx?Id=' },
  get report_hrStaffStatChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffStatChecks.aspx?Id=' },
  get report_childReferralsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildReferrals.aspx?Id=' },
  get report_childOOHURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildOOH.aspx?Id=' },
  get report_carerTrainingStatusURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerTrainingStatus.aspx?Id=' },
  get report_annualReviewDatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerAnnualReviewDates.aspx?Id=' },
  get report_carerDayLogEventsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerDaylogEvents.aspx?Id=' },
  get report_childDayLogEventsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildDaylogEvents.aspx?Id=' },
  get report_carerIncidentsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerIncidents.aspx?Id=' },
  get report_userLogHistoryURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/UserLogHistory.aspx?Id=' },
  get report_activeCarerContactDetailsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ActiveCarerContactDetails.aspx?Id=' },
  get report_claDocumentationURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CLADocumentation.aspx?Id=' },
  get report_fcDiaryRecordingsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/FCDiaryRecordings.aspx?Id=' },
  get report_unannouncedHomeVisitURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/UnannouncedHomeVisit.aspx?Id=' },
  get report_sourceOfEnquiryURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SourceOfEnquiry.aspx?Id=' },
  get report_applicantStatsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantsStats.aspx?Id=' },
  get report_applicantsAssessmentsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantAssessments.aspx?Id=' },
  get report_applicantsWithdrawnURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantsWithdrawn.aspx?Id=' },
  get report_ihvApplicantWithdrawnURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/IHVApplicantsWithdrawn.aspx?Id=' },
  get report_childReferralStatsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildReferralStats.aspx?Id=' },
  get report_carersBySocialWorkerURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarersBySocialWorker.aspx?Id=' },
  get report_schedule7URL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/Schedule7.aspx?Id=' },
  get report_childMedicalAppointmentsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildMedicalAppointments.aspx?Id=' },
  get report_shvCarerDatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SHVCarerDates.aspx?Id=' },
  get report_carerAuditURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerAudit.aspx?Id=' },
  get report_nfaReasonsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/NFAReasons.aspx?Id=' },
  get report_childSafecarePolicyURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildSafeCarePolicy.aspx?Id=' },
  get report_carerAllegationsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerAllegations.aspx?Id=' },
  get report_carerComplaintsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerComplaints.aspx?Id=' },
  get report_hrStaffSupervisionURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffSupervision.aspx?Id=' },
  get report_hrStaffAppraisalURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffAppraisal.aspx?Id=' },
  get report_hrStaffTrainingURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffTraining.aspx?Id=' },
  get report_childEducationInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildEducationInfo.aspx?Id=' },
  get report_childHealthInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildHealthInfo.aspx?Id=' },
  get report_childRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildRespitePlacements.aspx?Id=' },
  get report_ihvOldVersionURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/IHVOldVersion.aspx?Id=' },
  get report_advertisingAnalysisURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantAdvertisingAnalysis.aspx?Id=' },
  get report_shvOldVersionTutisURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SHVOldVersionTutis.aspx?Id=' },
  get report_childTherapeuticAssessmentScoreURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildTherapeuticAssessmentScore.aspx?Id=' },
  get report_carerPlacementRefusalURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerPlacementRefusal.aspx?Id=' },
  get report_childReferralInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildReferralInfo.aspx?Id=' },
  get report_claDocumentationCategoryURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CLADocumentationCategory.aspx?Id=' },
  get report_ecmProgressDatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ECMProgressDates.aspx?Id=' },
  get report_childrenBirthdayURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildrenBirthday.aspx?Id=' },
  get report_carerBirthdayURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerBirthday.aspx?Id=' },
  get report_carerPlacementsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerPlacements.aspx?Id=' },
  get report_childEducationCategoryURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildEducationCategory.aspx?Id=' },
  get report_childReportByDischargeReasonURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildReportByDischargeReason.aspx?Id=' },
  get report_fcPaymentsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/FCPayments.aspx?Id=' },
  get report_fcInvoiceURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/FCInvoice.aspx?Id=' },
  get report_laFinanceURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/LAFinance.aspx?Id=' },
  get report_shvOutcomesRatingsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SHVOutcomesRatings.aspx?Id=' },
  get report_carerDBSUpdateServiceURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerDBSUpdateService.aspx?Id=' },
  get report_qaManagementTrackerURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/QAManagementTracker.aspx?Id=' },
  get report_qaManagementReportURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/QAManagementReport.aspx?Id=' },
  get report_carerRespitePlacementsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerRespitePlacements.aspx?Id=' },
  get report_carerMedicalChecksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerMedicalChecksReport.aspx?Id=' },
  get report_childrenInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildrenInfo.aspx?Id=' },
  get report_childRiskAssessmentDatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildRiskAssessmentDates.aspx?Id=' },
  get report_backupCarersURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/BackupCarers.aspx?Id=' },
  get report_fcAllowanceURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/FCAllowance.aspx?Id=' },
  get report_referralsByCategoryURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ReferralsByCategory.aspx?Id=' },
  get report_childHospitalizationURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildHospitalization.aspx?Id=' },
  get report_childSHVDatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildSHVDates.aspx?Id=' },
  get report_placementRatesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/PlacementRates.aspx?Id=' },
  get report_staffLeavesURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffLeaves.aspx?Id=' },
  get report_childAuditURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildAudit.aspx?Id=' },
  get report_placementInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/PlacementInfo.aspx?Id=' },
  get report_panelRecommendationURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/PanelRecommendation.aspx?Id=' },
  get report_reviewOfficerRecommendationURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ReviewOfficerRecommendation.aspx?Id=' },
  get report_claReviewURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CLAReview.aspx?Id=' },
  get report_childPersonalGoalsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildPersonalGoals.aspx?Id=' },
  get report_carerOOHURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerOOH.aspx?Id=' },
  get report_applicantsStageInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ApplicantsStageInfo.aspx?Id=' },
  get report_fosteringHouseholdURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/FosteringHousehold.aspx?Id=' },
  get report_hrPanelMemberAppraisalURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRPanelMemberAppraisal.aspx?Id=' },
  get report_hrSSWSupervisionActionsURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRSSWSupervisionActions.aspx?Id=' },
  get report_hrStaffBirthdaysURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/HRStaffBirthdays.aspx?Id=' },
  get report_placementsByStaffUserURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/PlacementsByStaffUser.aspx?Id=' },
  get report_carerStatusInfoURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerStatusInfo.aspx?Id=' },
  get report_sswAnnualReviewURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SSWAnnualReview.aspx?Id=' },
  get report_childrensRisksURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildrensRisks.aspx?Id=' },
  get report_placementTrackerURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildPlacementTracker.aspx?Id=' },
  get report_shvfcsignatureURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/SHVFCSignature.aspx?Id=' },
  get report_childecmgoalsphotographURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildECMGoalsandPhotograph.aspx?Id=' },
  get report_carersignatureURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerSignature.aspx?Id=' },
  get report_childiroURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildIRO.aspx?Id=' },
  get report_childsignatureURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/ChildSignature.aspx?Id=' },
  get report_staffsignatureURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/StaffSignature.aspx?Id=' },
  get report_carerannualReviewNurtureURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerAnnualReviewNurture.aspx?Id=' },
  get report_carerannualReviewRainbowURL(): string { return 'https://fostering.starlight.inc/eCarePlusReports/CarerAnnualReviewRainbow.aspx?Id=' },
  get userSessionCheckTime(): number { return 1800 },
};
