import { BaseDTO } from '../../basedto';


export class ChildSpecificPlanDTO extends BaseDTO {
    ChildSpecificPlanId: number;
    ChildId: number;

    CarerParentId: number;
    SSWId: number;
    ReviewDate: Date = null;
    ReasonforUpdate: String;
    ChildSummary: String;
    SelfHarmBehaviour : number;
    SelfHarmBehaviourScore : number;
    SelfHarmBehaviourRating : number;
    SelfHarmBehaviourInfo : String;
    SuicideThreats : number;
    SuicideThreatsScore : number;
    SuicideThreatsRating : number;
    SuicideThreatsInfo : String;
    MedicalCondition : number;
    MedicalConditionScore : number;
    MedicalConditionRating : number;
    MedicalConditionInfo : String;
    HighRiskMedicalCondition : number;
    HighRiskMedicalConditionScore : number;
    HighRiskMedicalConditionRating : number;
    HighRiskMedicalConditionInfo : String;
    EatingDisorders : number;
    EatingDisordersScore : number;
    EatingDisordersRating : number;
    EatingDisordersInfo : String;
    VerbalViolenceOtherChildren  : number;
    VerbalViolenceOtherChildrenScore : number;
    VerbalViolenceOtherChildrenRating : number;
    VerbalViolenceOtherChildrenInfo : String;
    PhysicalViolenceOtherChildren : number;
    PhysicalViolenceOtherChildrenScore : number;
    PhysicalViolenceOtherChildrenRating : number;
    PhysicalViolenceOtherChildrenInfo : String;
    VerbalViolenceAdults : number;
    VerbalViolenceAdultsScore : number;
    VerbalViolenceAdultsRating : number;
    VerbalViolenceAdultsInfo : String;
    PhysicalViolenceAdults : number;
    PhysicalViolenceAdultsScore : number;
    PhysicalViolenceAdultsRating : number;
    PhysicalViolenceAdultsInfo : String;
    ViolenceCrueltyAnimals : number;
    ViolenceCrueltyAnimalsScore : number;
    ViolenceCrueltyAnimalsRating : number;
    ViolenceCrueltyAnimalsInfo : String;
    SexuallyHarmfulOthers  : number;
    SexuallyHarmfulOthersScore : number;
    SexuallyHarmfulOthersRating : number;
    SexuallyHarmfulOthersInfo : String;
    VulnerabilityAroundSexuality : number;
    VulnerabilityAroundSexualityScore : number;
    VulnerabilityAroundSexualityRating : number;
    VulnerabilityAroundSexualityInfo : String;
    ChildSexualExploitation : number;
    ChildSexualExploitationScore : number;
    ChildSexualExploitationRating : number;
    ChildSexualExploitationInfo : String;
    ChildCriminalExploitation : number;
    ChildCriminalExploitationScore : number;
    ChildCriminalExploitationRating : number;
    ChildCriminalExploitationInfo : String;
    RiskFireSetting : number;
    RiskFireSettingScore : number;
    RiskFireSettingRating : number;
    RiskFireSettingInfo : String;
    RiskDestructionToProperty : number;
    RiskDestructionToPropertyScore : number;
    RiskDestructionToPropertyRating : number;
    RiskDestructionToPropertyInfo : String;
    RiskOffendingBehaviour  : number;
    RiskOffendingBehaviourScore : number;
    RiskOffendingBehaviourRating : number;
    RiskOffendingBehaviourInfo : String;
    RiskRadicalisation : number;
    RiskRadicalisationScore : number;
    RiskRadicalisationRating : number;
    RiskRadicalisationInfo : String;
    RiskMakingAllegation : number;
    RiskMakingAllegationScore : number;
    RiskMakingAllegationRating : number;
    RiskMakingAllegationInfo : String;
    SmokingCigarettes : number;
    SmokingCigarettesScore : number;
    SmokingCigarettesRating : number;
    SmokingCigarettesInfo : String;
    RiskTakingDealingDrugs  : number;
    RiskTakingDealingDrugsScore : number;
    RiskTakingDealingDrugsRating : number;
    RiskTakingDealingDrugsInfo : String;
    RiskAlcoholConsumption  : number;
    RiskAlcoholConsumptionScore : number;
    RiskAlcoholConsumptionRating : number;
    RiskAlcoholConsumptionInfo : String;
    RiskAbsconding  : number;
    RiskAbscondingScore : number;
    RiskAbscondingRating : number;
    RiskAbscondingInfo : String;
    RiskSportsActivities   : number;
    RiskSportsActivitiesScore : number;
    RiskSportsActivitiesRating : number;
    RiskSportsActivitiesInfo : String;
    RiskTakingBehaviourAdrenaline   : number;
    RiskTakingBehaviourAdrenalineScore : number;
    RiskTakingBehaviourAdrenalineRating : number;
    RiskTakingBehaviourAdrenalineInfo : String;
    OtherRiskIdentified   : number;
    OtherRiskIdentifiedScore : number;
    OtherRiskIdentifiedRating : number;
    OtherRiskIdentifiedInfo: String;


    ChildPreferredName : String;
    HealthDisabilityDetails : String;
    HealthDisabilityStrategies : String;
    PersonalCareDetails : String;
    PersonalCareStrategies : String;
    ShowingAffectionDetails : String;
    ShowingAffectionStrategies : String;
    DailyRoutinesBedtimeDetails : String;
    DailyRoutinesBedtimeStrategies : String;
    PrivacyBathroomBedroomsDetails : String;
    PrivacyBathroomBedroomsStrategies : String;
    PlayDetails : String;
    PlayStrategies : String;
    SocialMediaPhotosDetails : String;
    SocialMediaPhotosStrategies : String;
    LearningSupportNeedsDetails : String;
    LearningSupportNeedsStrategies : String;
    LimitedSenseDangerDetails : String;
    LimitedSenseDangerStrategies : String;
    AdviceSelfStimulatorySexualisedDetails : String;
    AdviceSelfStimulatorySexualisedStrategies : String;
    VisitorsHomeDetails : String;
    VisitorsHomeStrategies : String;
    TravelTransportDetails : String;
    TravelTransportStrategies : String;
    GoingOutAloneDetails : String;
    GoingOutAloneStrategies : String;
    ContactWithFriendsFamilyDetails  : String;
    ContactWithFriendsFamilyStrategies : String;
    RegularVisitorsDetails : String;
    RegularVisitorsStrategies : String;
    ConfidentialitySecretsDetails : String;
    ConfidentialitySecretsStrategies : String;
    OtherDetails : String;
    OtherStrategies : String;
}